#!/command/with-contenv bash
# shellcheck shell=bash

port=$(sed -n '1p' "${CONFIG_DIR}/wireguard/forwarded_port")
echo "${port}" > "${CONFIG_DIR}/wireguard/forwarded_port"
echo "changed" >> "${CONFIG_DIR}/wireguard/forwarded_port"
