#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

umask "${UMASK}"

if [[ -n ${VPN_AUTO_PORT_FORWARD_TO_PORTS} ]]; then
    VPN_PORT_REDIRECTS=${VPN_AUTO_PORT_FORWARD_TO_PORTS}
    log_wrn "[FORWARDER] The variable [VPN_AUTO_PORT_FORWARD_TO_PORTS] is deprecated in favor of [VPN_PORT_REDIRECTS], please adjust your config!"
fi

if valid_port "${VPN_AUTO_PORT_FORWARD}"; then
    echo "${VPN_AUTO_PORT_FORWARD}" > "${CONFIG_DIR}/wireguard/forwarded_port"
    sleep_time=86400
else
    # Wait for pia/proton services to do their thing
    sleep 10
fi

while true; do
    if [[ -f "${CONFIG_DIR}/wireguard/forwarded_port" ]]; then
        port=$(sed -n '1p' "${CONFIG_DIR}/wireguard/forwarded_port")
        if valid_port "${port}"; then
            if [[ "${old_port}" != "${port}" ]]; then
                log_inf "[FORWARDER] Forwarded port is [${port}]."
                old_firewall_rules=$(nft -s list table inet hotio)
                IFS=',' read -ra redirects <<< "${VPN_PORT_REDIRECTS%,}"
                for redirect in "${redirects[@]}"; do
                    [[ ${redirect} == *@* ]] && continue
                    port_is_redirected="true"
                    redirect="${redirect//[[:space:]]/}"
                    internal="${redirect#*@}"
                    del_rule_redirect_port "${old_port}" "${internal}"
                    add_rule_redirect_port "${port}" "${internal}"
                    add_rule_expose_port "${internal}"
                done
                if [[ "${port_is_redirected}" != "true" ]]; then
                    del_rule_expose_port "${old_port}/tcp"
                    del_rule_expose_port "${old_port}/udp"
                    add_rule_expose_port "${port}/tcp"
                    add_rule_expose_port "${port}/udp"
                fi
                new_firewall_rules=$(nft -s list table inet hotio)
                if [[ "${old_firewall_rules}" != "${new_firewall_rules}" ]]; then
                    log_inf "[VPN] Firewall rules have changed, updated rules:"
                    echo "${new_firewall_rules}"
                fi
                # shellcheck source=/dev/null
                source "${APP_DIR}/forwarded_port_update_app"
                if [[ -f "${CONFIG_DIR}/wireguard/${VPN_CONF}-port.sh" ]]; then
                    log_inf "[FORWARDER] Script [${CONFIG_DIR}/wireguard/${VPN_CONF}-port.sh] found. Executing..."
                    bash "${CONFIG_DIR}/wireguard/${VPN_CONF}-port.sh"
                fi
                old_port="${port}"
                echo "${port}" > "${CONFIG_DIR}/wireguard/forwarded_port_validated"
                log_inf "[FORWARDER] Checking if forwarded port [${port}] is reachable..."
                i=0; while [[ ${i} -lt 5 ]]; do
                    ((i+=1))
                    sleep 5
                    if [[ $(curl -fsL -4 "https://portchecker.io/api/me/${port}" --header 'Accept: */*') != "True" ]]; then
                        [[ ${i} -eq 4 ]] && log_wrn "[FORWARDER] Forwarded port [${port}] is closed, no service is listening or couldn't reliably check the status."
                    else
                        log_inf "[FORWARDER] Forwarded port [${port}] is open."
                        break
                    fi
                done
            fi
        else
            log_err "[FORWARDER] The file [${CONFIG_DIR}/wireguard/forwarded_port] contains a value that's not a valid port!"
        fi
    else
        log_wrn "[FORWARDER] The file [${CONFIG_DIR}/wireguard/forwarded_port] was not found. Set [VPN_AUTO_PORT_FORWARD=false] if you don't plan on providing that file yourself."
    fi
    sleep "${sleep_time:-60}"
done
