#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

[[ ${VPN_ENABLED} == "true" ]] || exit 0

if [[ -n ${VPN_AUTO_PORT_FORWARD_TO_PORTS} ]]; then
    VPN_PORT_REDIRECTS=${VPN_AUTO_PORT_FORWARD_TO_PORTS}
    log_wrn "[VPN] The variable [VPN_AUTO_PORT_FORWARD_TO_PORTS] is deprecated in favor of [VPN_PORT_REDIRECTS], please adjust your config!"
fi

if ! capsh --print | grep -q "Current:.*cap_net_admin"; then
    log_err "[VPN] Not the right capabilities, add [--cap-add=NET_ADMIN] and remove [--privileged=true] if set! Exiting..."
    exit 1
fi

if ip a show docker0 up > /dev/null 2>&1; then
    log_err "[VPN] Docker network type [host] is not supported, use [bridge] instead! Exiting..."
    exit 1
fi

if [[ ! -d "${CONFIG_DIR}/wireguard/" ]]; then
    mkdir "${CONFIG_DIR}/wireguard"
    find "${CONFIG_DIR}/wireguard" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
    log_inf "[VPN] Created directory [${CONFIG_DIR}/wireguard]."
fi

if [[ -f "${CONFIG_DIR}/wireguard/${VPN_CONF}-pre.sh" ]]; then
    log_inf "[VPN] Script [${CONFIG_DIR}/wireguard/${VPN_CONF}-pre.sh] found. Executing..."
    bash "${CONFIG_DIR}/wireguard/${VPN_CONF}-pre.sh"
fi

if [[ ${VPN_PROVIDER} == "pia" ]]; then
    pia_download_wg
fi

if [[ ! -f "${CONFIG_DIR}/wireguard/${VPN_CONF}.conf" ]]; then
    log_err "[VPN] Configuration file [${CONFIG_DIR}/wireguard/${VPN_CONF}.conf] was not found! Exiting..."
    exit 1
fi

log_inf "[VPN] Creating interface [${VPN_CONF}]."

dos2unix -q -n "${CONFIG_DIR}/wireguard/${VPN_CONF}.conf" "/dev/shm/${VPN_CONF}.conf"
chmod 600 "/dev/shm/${VPN_CONF}.conf"
wg-quick strip "/dev/shm/${VPN_CONF}.conf" > "/dev/shm/${VPN_CONF}-stripped.conf"

ip link add dev "${VPN_CONF}" type wireguard

if [[ "$(cat "/proc/sys/net/ipv6/conf/${VPN_CONF}/disable_ipv6")" == "0" ]]; then
    ipv6_available="true"
    log_inf "[VPN] IPv6 support is available on interface [${VPN_CONF}]."
else
    log_inf "[VPN] IPv6 support is not available on interface [${VPN_CONF}]."
fi

ip_addresses=$(grep '^Address' "/dev/shm/${VPN_CONF}.conf" | awk -F '=' '{print $2}' | xargs)
for ip_address in ${ip_addresses//,/ }; do
    if valid4 "${ip_address}"; then
        ip_address=$(get4 "${ip_address}")
        ip -4 address add dev "${VPN_CONF}" "${ip_address}"
        ipv4_wanted="true"
        log_inf "[VPN] Added IPv4 address [${ip_address}] to interface [${VPN_CONF}]."
    fi
    if valid6 "${ip_address}" && [[ ${ipv6_available} == "true" ]]; then
        ip_address=$(get6 "${ip_address}")
        ip -6 address add dev "${VPN_CONF}" "${ip_address}"
        ipv6_wanted="true"
        log_inf "[VPN] Added IPv6 address [${ip_address}] to interface [${VPN_CONF}]."
    fi
    if valid6 "${ip_address}" && [[ ${ipv6_available} != "true" ]]; then
        log_wrn "[VPN] Failed adding IPv6 address [${ip_address}] to interface [${VPN_CONF}]."
    fi
done

ip_addresses=$(grep '^AllowedIPs' "/dev/shm/${VPN_CONF}-stripped.conf" | awk -F '=' '{print $2}' | xargs)
for ip_address in ${ip_addresses//,/ }; do
    if valid4 "${ip_address}" && [[ ${ipv4_wanted} == "true" ]]; then
        allowed_ips+="${ip_address},"
        ipv4_allowedips_found="true"
    fi
    if valid6 "${ip_address}" && [[ ${ipv6_wanted} == "true" ]]; then
        allowed_ips+="${ip_address},"
        ipv6_allowedips_found="true"
    fi
done

if [[ "${ipv4_wanted}" == "true" ]] && [[ "${ipv4_allowedips_found}" != "true" ]]; then
    allowed_ips+="0.0.0.0/0,"
    log_wrn "[VPN] IPv4 is wanted, but AllowedIPs for interface [${VPN_CONF}] has no IPv4 address configured. Added default [0.0.0.0/0]."
fi
if [[ "${ipv6_wanted}" == "true" ]] && [[ "${ipv6_allowedips_found}" != "true" ]]; then
    allowed_ips+="::/0,"
    log_wrn "[VPN] IPv6 is wanted, but AllowedIPs for interface [${VPN_CONF}] has no IPv6 address configured. Added default [::/0]."
fi

sed -i "s#^AllowedIPs.*#AllowedIPs = ${allowed_ips%,}#" "/dev/shm/${VPN_CONF}-stripped.conf"
log_inf "[VPN] AllowedIPs are [${allowed_ips%,}] for interface [${VPN_CONF}]."

wg setconf "${VPN_CONF}" "/dev/shm/${VPN_CONF}-stripped.conf"
ip link set up dev "${VPN_CONF}"
log_inf "[VPN] Interface [${VPN_CONF}] is online."

default4_route_json=$(ip -4 -j route show to default | jq -rc '.[]')
default4_interface=$(jq -r '.dev' <<< "${default4_route_json}")
default4_gateway=$(jq -r '.gateway' <<< "${default4_route_json}")

default6_route_json=$(ip -6 -j route show to default | jq -rc '.[]')
default6_interface=$(jq -r '.dev' <<< "${default6_route_json}")
default6_gateway=$(jq -r '.gateway' <<< "${default6_route_json}")

ip_addr_json=$(ip -j address show)
interfaces=$(jq -rc '.[]|select((.ifname|startswith("eth")) or (.ifname|startswith("enp")))|.ifname' <<< "${ip_addr_json}")
while IFS=$'\n' read -r interface; do
    networks=$(jq -rc --arg interface "${interface}" '.[]|select((.ifname==$interface))|.addr_info[]' <<< "${ip_addr_json}")
    while IFS=$'\n' read -r network; do
        note="         "
        local=$(jq -r '.local' <<< "${network}")
        prefixlen=$(jq -r '.prefixlen' <<< "${network}")
        net="$(getnet "${local}/${prefixlen}")/${prefixlen}"
        network_list+="${interface} ${local} ${net},"
        if [[ "${net}" == "$(get4net "${default4_gateway}/${prefixlen}")/${prefixlen}" ]]; then
            note="[default]"
            default4_address="${local}"
        fi
        if [[ "${net}" == "$(get6net "${default6_gateway}/${prefixlen}")/${prefixlen}" ]]; then
            note="[default]"
            default6_address="${local}"
        fi
        log_inf "[VPN] Found network ${note}[${interface}][${local}][${net}]."
    done <<< "${networks}"
done <<< "${interfaces}"

vpn_endpoint=$(wg show "${VPN_CONF}" | grep 'endpoint:' | awk -F ': ' '{print $2}' | sed -e 's#\[##' -e 's#\]##')
vpn_endpoint_ip="${vpn_endpoint%:*}"
vpn_endpoint_port="${vpn_endpoint##*:}"
if valid4 "${vpn_endpoint_ip}" && valid4 "${default4_gateway}"; then
    ip -4 route add "${vpn_endpoint_ip}" via "${default4_gateway}" dev "${default4_interface}" table "${vpn_endpoint_port}"
    ip -4 rule add ipproto udp dport "${vpn_endpoint_port}" to "${vpn_endpoint_ip}" table "${vpn_endpoint_port}" iif lo
    ip -4 rule add ipproto udp sport "${vpn_endpoint_port}" from "${vpn_endpoint_ip}" table "${vpn_endpoint_port}"
    log_inf "[VPN] Routing IPv4 traffic for [${vpn_endpoint_ip}][${vpn_endpoint_port}][ENDPOINT] via interface [${default4_interface}]."
fi
if valid4 "${vpn_endpoint_ip}" && ! valid4 "${default4_gateway}"; then
    log_err "[VPN] There is no IPv4 default gateway for [${vpn_endpoint_ip}][${vpn_endpoint_port}][ENDPOINT]! Exiting..."
    exit 1
fi
if valid6 "${vpn_endpoint_ip}" && valid6 "${default6_gateway}"; then
    ip -6 route add "${vpn_endpoint_ip}" via "${default6_gateway}" dev "${default6_interface}" table "${vpn_endpoint_port}"
    ip -6 rule add ipproto udp dport "${vpn_endpoint_port}" to "${vpn_endpoint_ip}" table "${vpn_endpoint_port}" iif lo
    ip -6 rule add ipproto udp sport "${vpn_endpoint_port}" from "${vpn_endpoint_ip}" table "${vpn_endpoint_port}"
    log_inf "[VPN] Routing IPv6 traffic for [${vpn_endpoint_ip}][${vpn_endpoint_port}][ENDPOINT] via interface [${default6_interface}]."
fi
if valid6 "${vpn_endpoint_ip}" && ! valid6 "${default6_gateway}"; then
    log_err "[VPN] There is no IPv6 default gateway for [${vpn_endpoint_ip}][${vpn_endpoint_port}][ENDPOINT]! Exiting..."
    exit 1
fi

IFS=',' read -ra lan_networks <<< "${VPN_LAN_NETWORK%,}"
for lan_network in "${lan_networks[@]}"; do
    lan_network="${lan_network//[[:space:]]/}"
    if valid4 "${lan_network}" && valid4 "${default4_gateway}"; then
        ip -4 route add "${lan_network}" via "${default4_gateway}" dev "${default4_interface}"
        log_inf "[VPN] Routing IPv4 traffic for [${lan_network}][LAN] via interface [${default4_interface}]."
    fi
    if valid6 "${lan_network}" && valid6 "${default6_gateway}"; then
        ip -6 route add "${lan_network}" via "${default6_gateway}" dev "${default6_interface}"
        log_inf "[VPN] Routing IPv6 traffic for [${lan_network}][LAN] via interface [${default6_interface}]."
    fi
done

if valid4 "${default4_gateway}" || [[ "${ipv4_wanted}" == "true" ]]; then
    ip -4 route del default > /dev/null 2>&1 || true
    ip -4 route add default dev "${VPN_CONF}"
    log_inf "[VPN] Routing all other IPv4 traffic via interface [${VPN_CONF}]."
fi
if valid6 "${default6_gateway}" || [[ "${ipv6_wanted}" == "true" ]]; then
    ip -6 route del default > /dev/null 2>&1 || true
    ip -6 route add default dev "${VPN_CONF}"
    log_inf "[VPN] Routing all other IPv6 traffic via interface [${VPN_CONF}]."
fi

IFS=',' read -ra ports <<< "${WEBUI_PORTS%,}"
for port in "${ports[@]}"; do
    exposed_ports+="${port//[[:space:]]/},"
done
IFS=',' read -ra ports <<< "${VPN_EXPOSE_PORTS_ON_LAN%,}"
for port in "${ports[@]}"; do
    exposed_ports+="${port//[[:space:]]/},"
done

# Create table and chains
nft add table inet hotio
nft add chain inet hotio forward    '{ type filter hook forward    priority 0 ; policy drop; }'
nft add chain inet hotio input      '{ type filter hook input      priority 0 ; policy drop; }'
nft add chain inet hotio output     '{ type filter hook output     priority 0 ; policy drop; }'
nft add chain inet hotio prerouting '{ type nat    hook prerouting priority -100 ; }'

## INPUT RULES

# Allow incoming ping
#nft add rule inet hotio input icmp type echo-request limit rate 4/second counter accept
#nft add rule inet hotio input icmpv6 type echo-request limit rate 4/second counter accept

# Allow all incoming traffic from LAN if VPN_LAN_LEAK_ENABLED=true
if [[ ${VPN_LAN_LEAK_ENABLED} == "true" ]]; then
    IFS=',' read -ra lan_networks <<< "${VPN_LAN_NETWORK%,}"
    for lan_network in "${lan_networks[@]}"; do
        lan_network="${lan_network//[[:space:]]/}"
        valid4 "${lan_network}" && valid4 "${default4_address}" && \
            nft add rule inet hotio input iifname "${default4_interface}" ip saddr "${lan_network}" ip daddr "${default4_address}" counter accept
        valid6 "${lan_network}" && valid6 "${default6_address}" && \
            nft add rule inet hotio input iifname "${default6_interface}" ip6 saddr "${lan_network}" ip6 daddr "${default6_address}" counter accept
    done
fi

# Allow incoming traffic from LAN to port
IFS=',' read -ra ports <<< "${exposed_ports%,}"
for port in "${ports[@]}"; do
    if [[ ${VPN_LAN_LEAK_ENABLED} != "true" ]]; then
        IFS=',' read -ra lan_networks <<< "${VPN_LAN_NETWORK%,}"
        for lan_network in "${lan_networks[@]}"; do
            lan_network="${lan_network//[[:space:]]/}"
            valid4 "${lan_network}" && valid4 "${default4_address}" && \
                nft add rule inet hotio input iifname "${default4_interface}" "${port##*/}" dport "${port%/*}" ip saddr "${lan_network}" ip daddr "${default4_address}" counter accept
            valid6 "${lan_network}" && valid6 "${default6_address}" && \
                nft add rule inet hotio input iifname "${default6_interface}" "${port##*/}" dport "${port%/*}" ip6 saddr "${lan_network}" ip6 daddr "${default6_address}" counter accept
        done
    fi
done

# Allow incoming traffic on local networks
IFS=',' read -ra networks <<< "${network_list%,}"
for network in "${networks[@]}"; do
    IFS=' ' read -ra part <<< "${network}"
    valid4 "${part[1]}" && \
        nft add rule inet hotio input iifname "${part[0]}" ip saddr "${part[2]}" ip daddr "${part[1]}" counter accept
    valid6 "${part[1]}" && \
        nft add rule inet hotio input iifname "${part[0]}" ip6 saddr "${part[2]}" ip6 daddr "${part[1]}" counter accept
done

# Allow incoming traffic from vpn endpoint
valid4 "${vpn_endpoint_ip}" && valid4 "${default4_address}" && \
    nft add rule inet hotio input iifname "${default4_interface}" udp sport "${vpn_endpoint_port}" ip saddr "${vpn_endpoint_ip}" ip daddr "${default4_address}" counter accept
valid6 "${vpn_endpoint_ip}" && valid6 "${default6_address}" && \
    nft add rule inet hotio input iifname "${default6_interface}" udp sport "${vpn_endpoint_port}" ip6 saddr "${vpn_endpoint_ip}" ip6 daddr "${default6_address}" counter accept

# Allow incoming traffic from vpn and lo
nft add rule inet hotio input iifname "${VPN_CONF}" ct state established,related counter accept
nft add rule inet hotio input iifname "lo" counter accept

# Allow incoming icmpv6 stuff
valid6 "${vpn_endpoint_ip}" && \
    nft add rule inet hotio input icmpv6 type '{ nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert }' counter accept

## OUTPUT RULES

# Allow outgoing ping
#nft add rule inet hotio output icmp type echo-request counter accept
#nft add rule inet hotio output icmpv6 type echo-request counter accept

# Allow all outgoing traffic to LAN if VPN_LAN_LEAK_ENABLED=true
if [[ ${VPN_LAN_LEAK_ENABLED} == "true" ]]; then
    IFS=',' read -ra lan_networks <<< "${VPN_LAN_NETWORK%,}"
    for lan_network in "${lan_networks[@]}"; do
        lan_network="${lan_network//[[:space:]]/}"
        valid4 "${lan_network}" && valid4 "${default4_address}" && \
            nft add rule inet hotio output oifname "${default4_interface}" ip saddr "${default4_address}" ip daddr "${lan_network}" counter accept
        valid6 "${lan_network}" && valid6 "${default6_address}" && \
            nft add rule inet hotio output oifname "${default6_interface}" ip6 saddr "${default6_address}" ip6 daddr "${lan_network}" counter accept
    done
fi

# Allow outgoing traffic to LAN from port
IFS=',' read -ra ports <<< "${exposed_ports%,}"
for port in "${ports[@]}"; do
    if [[ ${VPN_LAN_LEAK_ENABLED} != "true" ]]; then
        IFS=',' read -ra lan_networks <<< "${VPN_LAN_NETWORK%,}"
        for lan_network in "${lan_networks[@]}"; do
            lan_network="${lan_network//[[:space:]]/}"
            valid4 "${lan_network}" && valid4 "${default4_address}" && \
                nft add rule inet hotio output oifname "${default4_interface}" "${port##*/}" sport "${port%/*}" ip saddr "${default4_address}" ip daddr "${lan_network}" counter accept
            valid6 "${lan_network}" && valid6 "${default6_address}" && \
                nft add rule inet hotio output oifname "${default6_interface}" "${port##*/}" sport "${port%/*}" ip6 saddr "${default6_address}" ip6 daddr "${lan_network}" counter accept
        done
    fi
done

# Allow outgoing traffic on local networks
IFS=',' read -ra networks <<< "${network_list%,}"
for network in "${networks[@]}"; do
    IFS=' ' read -ra part <<< "${network}"
    valid4 "${part[1]}" && \
        nft add rule inet hotio output oifname "${part[0]}" ip saddr "${part[1]}" ip daddr "${part[2]}" counter accept
    valid6 "${part[1]}" && \
        nft add rule inet hotio output oifname "${part[0]}" ip6 saddr "${part[1]}" ip6 daddr "${part[2]}" counter accept
done

# Allow outgoing traffic to vpn endpoint
valid4 "${vpn_endpoint_ip}" && valid4 "${default4_address}" && \
    nft add rule inet hotio output oifname "${default4_interface}" udp dport "${vpn_endpoint_port}" ip saddr "${default4_address}" ip daddr "${vpn_endpoint_ip}" counter accept
valid6 "${vpn_endpoint_ip}" && valid6 "${default6_address}" && \
    nft add rule inet hotio output oifname "${default6_interface}" udp dport "${vpn_endpoint_port}" ip6 saddr "${default6_address}" ip6 daddr "${vpn_endpoint_ip}" counter accept

# Allow outgoing traffic to vpn and lo
nft add rule inet hotio output oifname "${VPN_CONF}" counter accept
nft add rule inet hotio output oifname "lo" counter accept

# Allow outgoing icmpv6 stuff
valid6 "${vpn_endpoint_ip}" && \
    nft add rule inet hotio output icmpv6 type '{ nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert }' counter accept

## REDIRECTS and EXPOSED PORTS

IFS=',' read -ra forward_ports <<< "${VPN_PORT_REDIRECTS%,}"
for forward_port in "${forward_ports[@]}"; do
    [[ ! ${forward_port} == *@* ]] && continue
    forward_port="${forward_port//[[:space:]]/}"
    external="${forward_port%@*}"
    internal="${forward_port#*@}"
    add_rule_redirect_port "${external}" "${internal}"
    add_rule_expose_port "${internal}"
done

# List rules
log_inf "[VPN] Firewall rules:"
nft -s list table inet hotio

if [[ -f "${CONFIG_DIR}/wireguard/${VPN_CONF}-post.sh" ]]; then
    log_inf "[VPN] Script [${CONFIG_DIR}/wireguard/${VPN_CONF}-post.sh] found. Executing..."
    bash "${CONFIG_DIR}/wireguard/${VPN_CONF}-post.sh"
fi

log_inf "[VPN] Performing internet connectivity tests, please wait..."

echo "nameserver 1.1.1.1" > "/etc/resolv.conf"
ip4=$(curl -fsL -4 --retry 5 --retry-max-time 60 --max-time 10 wtfismyip.com/json | jq -re '"[\(.YourFuckingLocation)] [\(.YourFuckingISP)] [\(.YourFuckingIPAddress)]."' || true)
if [[ -z ${ip4} ]]; then
    log_err "[VPN] [IPV4] IP lookup failed!"
    [[ ${VPN_HEALTHCHECK_ENABLED} == "true" ]] && exit 1
else
    ping4=$(ping -c 5 1.1.1.1 2> /dev/null | tail -1 | awk -F ' = ' '{print $2}')
    log_inf "[VPN] [IPV4] [PING: ${ping4}] ${ip4}"
fi

if [[ ${ipv6_wanted} == "true" ]]; then
    echo "nameserver 2606:4700:4700::1111" > "/etc/resolv.conf"
    ip6=$(curl -fsL -6 --retry 5 --retry-max-time 60 --max-time 10 wtfismyip.com/json | jq -re '"[\(.YourFuckingLocation)] [\(.YourFuckingISP)] [\(.YourFuckingIPAddress)]."' || true)
    if [[ -z ${ip6} ]]; then
        log_err "[VPN] [IPV6] IP lookup failed!"
        [[ ${VPN_HEALTHCHECK_ENABLED} == "true" ]] && exit 1
    else
        ping6=$(ping6 -c 5 2606:4700:4700::1111 2> /dev/null | tail -1 | awk -F ' = ' '{print $2}')
        log_inf "[VPN] [IPV6] [PING: ${ping6}] ${ip6}"
    fi
fi

exit 0
