#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

umask "${UMASK}"

ip_addresses=$(grep '^Address' "/dev/shm/${VPN_CONF}.conf" | awk -F '=' '{print $2}' | xargs)
for ip_address in ${ip_addresses//,/ }; do
    if valid4 "${ip_address}"; then
        ip_address=$(ipcalc -4 -s -a --no-decorate "${ip_address}")
        vpn_gw="${ip_address%.*}.1"
        break
    fi
done

while true; do
    if ! natpmpc -g "${vpn_gw}" &> /dev/null; then
        log_wrn "[PROTON] Endpoint [${vpn_gw}] does not support port forwarding!"
    else
        port=$(natpmpc -g "${vpn_gw}" -a 1 0 udp 60 | grep -P -o -m 1 '(?<=Mapped public port\s)\d+')
        if [[ -n "${port}" ]]; then
            natpmpc -g "${vpn_gw}" -a 1 0 tcp 60 &> /dev/null
            echo "${port}" > "${CONFIG_DIR}/wireguard/forwarded_port"
        else
            log_wrn "[PROTON] Port forwarding failed!"
        fi
    fi
    sleep 45
done
