---
kind: pipeline
name: checks

trigger:
  event:
    - tag
    - push

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - tag
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    cache_from: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    build_args:
      - ARCH_S6=amd64
      - ARCH_RCLONE=amd64
    tags:
      - ${DRONE_TAG=develop}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - tag
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    cache_from: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    build_args:
      - ARCH_S6=aarch64
      - ARCH_RCLONE=arm64
    tags:
      - ${DRONE_TAG=develop}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

trigger:
  event:
    - tag
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    cache_from: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    build_args:
      - ARCH_S6=arm
      - ARCH_RCLONE=arm
    tags:
      - ${DRONE_TAG=develop}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: manifest

trigger:
  event:
    - tag
    - push

steps:
- name: manifest
  image: plugins/manifest
  pull: always
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl

depends_on:
  - linux-amd64
  - linux-arm64
  - linux-arm

---
kind: pipeline
name: dockerhub-description

trigger:
  event:
    - tag
    - push

steps:
- name: dockerhub-description
  image: peterevans/dockerhub-description:2.0.0
  pull: always
  environment:
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPOSITORY: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
