#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

#IMAGE_STATS=ewogICJhcHAiOiAicWJpdHRvcnJlbnQiLAogICJpbWFnZSI6ICJob3Rpby9xYml0dG9ycmVudDpyZWxlYXNlIiwKICAicmV2aXNpb24iOiAiMzcwYjNhNiIsCiAgInZlcnNpb24iOiAiNC42LjMiCn0K
IMAGE_STATS=$(base64 --decode <<< "${IMAGE_STATS}")
image=$(jq -r '.image' <<< "${IMAGE_STATS}")
revision=$(jq -r '.revision' <<< "${IMAGE_STATS}")
version=$(jq -r '.version' <<< "${IMAGE_STATS}")
app_uri=$(jq -r 'if .app != "" then "/containers/\(.app)" else empty end' <<< "${IMAGE_STATS}")

echo -ne "
$(figlet "hotio")
Donate:        https://hotio.dev/donate
Documentation: https://hotio.dev${app_uri}
Support:       https://hotio.dev/discord
Image:         ${image}
Revision:      ${revision}
Version:       ${version}
OS:            $(uname -s) $(uname -r) $(uname -m)

----------------------------------------------------------------------
ENVIRONMENT BASE
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
PRIVOXY_ENABLED=${PRIVOXY_ENABLED}
UNBOUND_ENABLED=${UNBOUND_ENABLED}
UNBOUND_NAMESERVERS=${UNBOUND_NAMESERVERS}
VPN_ENABLED=${VPN_ENABLED}"
[[ ${VPN_ENABLED} == true ]] && echo -ne "
VPN_CONF=${VPN_CONF}
VPN_PROVIDER=${VPN_PROVIDER}
VPN_LAN_NETWORK=${VPN_LAN_NETWORK}
VPN_LAN_LEAK_ENABLED=${VPN_LAN_LEAK_ENABLED}
VPN_EXPOSE_PORTS_ON_LAN=${VPN_EXPOSE_PORTS_ON_LAN}
VPN_AUTO_PORT_FORWARD=${VPN_AUTO_PORT_FORWARD}
VPN_PORT_REDIRECTS=${VPN_PORT_REDIRECTS}
VPN_HEALTHCHECK_ENABLED=${VPN_HEALTHCHECK_ENABLED}
VPN_NAMESERVERS=${VPN_NAMESERVERS}
VPN_PIA_USER=$(mask "${VPN_PIA_USER}")
VPN_PIA_PASS=$(mask "${VPN_PIA_PASS}")
VPN_PIA_PREFERRED_REGION=${VPN_PIA_PREFERRED_REGION}
VPN_PIA_DIP_TOKEN=$([[ ${VPN_PIA_DIP_TOKEN} != "no" ]] && mask "${VPN_PIA_DIP_TOKEN}" || echo "${VPN_PIA_DIP_TOKEN}")
VPN_PIA_PORT_FORWARD_PERSIST=${VPN_PIA_PORT_FORWARD_PERSIST}"
echo -ne "
----------------------------------------------------------------------

"

log_inf "Executing usermod..."
mkdir "/tmp/temphome"
usermod -d "/tmp/temphome" hotio > /dev/null
usermod -o -u "${PUID}" hotio > /dev/null
usermod -d "${CONFIG_DIR}" hotio > /dev/null
rm -rf "/tmp/temphome"
log_inf "Executing groupmod..."
groupmod -o -g "${PGID}" hotio > /dev/null

log_inf "Taking ownership of [${CONFIG_DIR}]."
find "${CONFIG_DIR}" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
