#!/command/with-contenv bash
# shellcheck shell=bash

if [[ "${PRIVOXY_ENABLED}" != true ]]; then
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/service-privoxy
fi

if [[ "${VPN_PROVIDER}" != "proton" ]] || [[ "${VPN_ENABLED}" != true ]] || [[ "${VPN_AUTO_PORT_FORWARD}" != true ]]; then
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/service-proton
fi

if [[ "${VPN_PROVIDER}" != "pia" ]] || [[ "${VPN_ENABLED}" != true ]] || [[ "${VPN_AUTO_PORT_FORWARD}" != true ]]; then
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/service-pia
fi
