#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

umask "${UMASK}"

if [[ -f "${CONFIG_DIR}/unbound.conf" ]]; then
    cp "${CONFIG_DIR}/unbound.conf" "/dev/shm/unbound.conf"
else
    cp "${APP_DIR}/unbound.conf" "/dev/shm/unbound.conf"
fi

setup_nameservers

echo "nameserver 127.0.0.1" > "/etc/resolv.conf"

/usr/sbin/unbound -c "/dev/shm/unbound.conf" -d -p
