#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "# Unbound enabled" > "/etc/resolv.conf"
echo "nameserver 127.0.0.1" >> "/etc/resolv.conf"

/usr/sbin/unbound -c "${APP_DIR}/unbound.conf" -d -p
