#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/general-functions

umask "${UMASK}"

log_inf "[VPN] Healthcheck active."

while true; do
    sleep 600
    if ! curl --retry 600 --retry-max-time 600 --max-time 10 https://one.one.one.one > /dev/null 2>&1; then
        log_err "[VPN] Healthcheck failed! Exiting..."
        exit 110
    fi
done
