#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "[INF] [$(date '+%Y-%m-%d %H:%M:%S')] [VPN] Healthcheck active."

while true; do
    sleep 600
    if ! curl --retry 600 --retry-max-time 600 --max-time 10 https://one.one.one.one > /dev/null 2>&1; then
        echo "[ERR] [$(date '+%Y-%m-%d %H:%M:%S')] [VPN] Healthcheck failed! Exiting..."
        exit 110
    fi
done
