name: update-on-call

on:
  workflow_call:

jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.branches.outputs.branches }}
    steps:
      - name: Get all branches for the repository
        id: branches
        env:
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branches=$(curl -fsSL --header "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/repos/${REPOSITORY}/branches" | jq -re '.[] | select(.name!="workflows") | [.name] | @csv' | paste -sd, -)
          echo "branches=[${branches}]" >> "$GITHUB_OUTPUT"

  update:
    needs: get-branches
    concurrency:
      group: ${{ github.repository }}-update-${{ matrix.branches }}
      cancel-in-progress: true
    strategy:
      matrix:
        branches: ${{ fromJSON(needs.get-branches.outputs.branches) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branches }}
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Login to ghcr.io
        continue-on-error: true
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update meta.json
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -f update-versions.sh ]]; then
            bash update-versions.sh
          else
            while read -r line; do
                key="${line%%=*}"
                key="${key%__command}"
                command="${line#*=}"
                value=$(eval "${command}")
                json=$(cat meta.json)
                jq --sort-keys --arg key "$key" --arg value "$value" '.[$key] = $value' <<< "${json}" > meta.json
                echo "Result: [${key}] [${command}] [${value}]"
            done < <(jq -r 'to_entries[] | [(.key),.value] | join("=")' < meta.json | grep '__command')
          fi

      - name: Check for upstream image changes
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [[ -f update-upstream.sh ]] && \
            bash update-upstream.sh

      - name: Update packages.txt
        continue-on-error: true
        if: (!endsWith(github.ref_name, 'pr'))
        env:
          BRANCH:     ${{ matrix.branches }}
          REPOSITORY: ${{ github.repository }}
        run: |
          docker run --quiet --rm --entrypoint="" -v ./:/repo -e PACKAGES="/repo/packages.txt" "ghcr.io/${REPOSITORY}:${BRANCH}" \
            sh -c 'if grep -q alpine < /etc/os-release; then apk upgrade --no-cache --available >/dev/null 2>&1 && apk -v info 2>/dev/null | sort > ${PACKAGES}; else export DEBIAN_FRONTEND=noninteractive && apt-get update >/dev/null 2>&1 && apt-get upgrade -y >/dev/null 2>&1 && dpkg-query --showformat="\${Package}-\${Version}\n" --show 2>/dev/null | sort > ${PACKAGES}; fi'

      - name: Commit changes
        env:
          BRANCH: ${{ matrix.branches }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add meta.json || true
          git add packages.txt || true
          commit_message="Version, Upstream or Packages update"
          [[ "${BRANCH}" == *pr ]] && commit_message+=" [skip ci]"
          if git commit -m "${commit_message}"; then
            git push
          fi
