#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

figlet "${APP}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
VERSION=${VERSION}
BACKUP=${BACKUP}
TZ=${TZ}
RCLONE=${RCLONE}
RAR2FS=${RAR2FS}
----------------------------------------------------------------------
"

groupmod -o -g "${PGID}" hotio
usermod -o -u "${PUID}" hotio

if [[ ! -d "${CONFIG_DIR}/app" ]]; then
    mkdir "${CONFIG_DIR}/app"
    chown hotio:hotio "${CONFIG_DIR}/app"
fi

if [[ ! -d "${CONFIG_DIR}/app-backups" ]] && [[ "${BACKUP}" == "yes" ]]; then
    mkdir "${CONFIG_DIR}/app-backups"
    chown hotio:hotio "${CONFIG_DIR}/app-backups"
fi
