#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

figlet "${APP}"

echo "
----------------------------------------------------------------------
DONATIONS
----------------------------------------------------------------------
NANO: xrb_1bxqm6nsm55s64rgf8f5k9m795hda535to6y15ik496goatakpupjfqzokfc
BTC: 39W6dcaG3uuF5mZTRL4h6Ghem74kUBHrmz
LTC: MMUFcGLiK6DnnHGFnN2MJLyTfANXw57bDY
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID            | ${PUID}
PGID            | ${PGID}
UMASK           | ${UMASK}
VERSION         | ${VERSION}
BACKUP          | ${BACKUP}
TZ              | ${TZ}
RCLONE          | ${RCLONE}
RAR2FS          | ${RAR2FS}
----------------------------------------------------------------------
"

groupmod -o -g "${PGID}" hotio
usermod -o -u "${PUID}" hotio

if [[ ! -d "${CONFIG_DIR}/app" ]]; then
    mkdir "${CONFIG_DIR}/app"
    chown hotio:hotio "${CONFIG_DIR}/app"
fi

if [[ ! -d "${CONFIG_DIR}/app-backups" ]] && [[ "${BACKUP}" == "yes" ]]; then
    mkdir "${CONFIG_DIR}/app-backups"
    chown hotio:hotio "${CONFIG_DIR}/app-backups"
fi
