#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"
shopt -s nullglob

if [[ -d "${CONFIG_DIR}/scripts.d" ]]; then
    for script in "${CONFIG_DIR}/scripts.d/"*; do
        ${script}
    done
fi
